<template><p>##从一个简单的例子开始</p>
<p>开篇讲到了，为了满足高并发下网络请求，引入了NIO的概念。Netty是针对NIO的实现，在NIO封装，网络调用，数据处理以及性能优化等方面都有不俗的表现。</p>
<p>学习架构最容易的方式就是从实例入手，从客户端访问服务端的代码来看看Netty是如何运作的。再一次介绍代码中调用的组件以及组件的工作原理。</p>
<p>假设有一个客户端去调用一个服务端，假设服务端叫做EchoServer，客户端叫做EchoClient，用Netty架构实现代码如下。</p>
<p>服务端代码</p>
<p>构建服务器端，假设服务器接受客户端传来的信息，然后在控制台打印。首先，生成EchoServer，在构造函数中传入需要监听的端口号。</p>
<p>接下来就是服务的启动方法：</p>
<p>Server的启动方法涉及到了一些组件的调用，例如<code>EventLoopGroup</code>，<code>Channel</code>。这些会在后面详细讲解。</p>
<p>这里有个大致的印象就好：</p>
<p>创建<code>EventLoopGroup</code>。</p>
<p>创建<code>ServerBootstrap</code>。</p>
<p>指定所使用的NIO传输<code>Channel</code>。</p>
<p>使用指定的端口设置套接字地址。</p>
<p>添加一个ServerHandler到Channel的ChannelPipeline。</p>
<p>异步地绑定服务器；调用<code>sync()</code>方法阻塞等待直到绑定完成。</p>
<p>获取Channel的CloseFuture，并且阻塞当前线程直到它完成。</p>
<p>关闭EventLoopGroup，释放所有的资源。</p>
<p><code>NettyServer</code>启动以后会监听某个端口的请求，当接受到了请求就需要处理了。在Netty中客户端请求服务端，被称为“入站”操作。</p>
<p>可以通过<code>ChannelInboundHandlerAdapter</code>实现，具体内容如下：</p>
<p>从上面的代码可以看出，服务端处理的代码包含了三个方法。这三个方法都是根据事件触发的。</p>
<p>他们分别是：</p>
<p>当接收到消息时的操作，<code>channelRead</code>。消息读取完成时的方法，<code>channelReadComplete</code>。出现异常时的方法，<code>exceptionCaught</code>。</p>
<p>客户端和服务端的代码基本相似，在初始化时需要输入服务端的Port和IP。</p>
</template>
